security:
  oauth2:
    client: 
      accessTokenUri: http://localhost:8888/oauth/token
      userAuthorizationUri: http://localhost:8888/oauth/authorize
      clientId: clientId
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:8888/user
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/employeesdb
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect